import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center pt-8  ${comfortaa.className}`}>
        <h1 className="light text-h1 bg-gradient-to-r from-primary to-secondary text-transparent bg-clip-text mb-8 font-semibold">
          To Do App
        </h1>
        {children}
      </body>
    </html>
  );
}
