"use client";
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "@/app/globals.css";
import { useSession, signOut } from "next-auth/react";

const comfortaa = Comfortaa({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: session, status } = useSession();

  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center pt-8  ${comfortaa.className}`}>
        <div className="fixed w-full">
          <button
            onClick={() =>
              signOut({
                redirect: false,
                callbackUrl: "http://localhost:3000/",
              })
            }
            className="absolute right-2">
            Sign out
          </button>
        </div>
        {children}
      </body>
    </html>
  );
}
