import type { Metadata } from "next";

import "@/app/globals.css";

import SessionProvider from "@/app/components/SessionProvider";
import AuthButton from "@/app/components/authButton";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <SessionProvider session={session}>
      <AuthButton>Sign out</AuthButton>
      <div className="w-full h-full"> {children}</div>
    </SessionProvider>
  );
}
